all:
	javac Main.java -Xlint:all
	java -Xms1024M -Xmx1024M Main
essential:
	javac Main.java -Xlint:all
	java -Xms1024M -Xmx1024M Main basic random_seoul large1 large2
changing:
	javac Main.java -Xlint:all
	java -Xms1024M -Xmx1024M Main random_seoul_changing
aux:
	javac Auxiliary.java -Xlint:all
clean:
	rm -f *.class y.out y.err
